[package]
name = "archors"
version = "0.1.0"
edition = "2021"
description = "Tool for single Ethereum archival block state proofs"

[workspace]
members = [
    "archors-verify",
    "archors-tracer",
    "archors-inventory",
]

[dependencies]
archors_inventory = { path = "archors-inventory"}
archors_tracer = { path = "archors-tracer"}
archors_verify = { path = "archors-verify"}

[dev-dependencies]
anyhow = "1.0.69"
tokio = { version = "1.26.0", features = ["full"] }
