[package]
name = "archors_interpret"
version = "0.1.0"
edition = "2021"
definition = "Create a readable summary of an EIP-3155 Ethereum transaction trace"

[dependencies]
alloy-primitives = "0.2.0"
anyhow = "1.0.69"
serde = {  version = "1.0.152", features = ["derive"] }
serde_json = "1.0.94"
thiserror = "1.0.40"
